package com.sjia.Leetcode;

public class FindStringDifference {
    // #389. Find the Difference    https://leetcode.com/problems/find-the-difference/description/

    /*
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Input: s = "abcd", t = "abcde"  Output: "e"
    Input: s = "", t = "y"  Output: "y"
     */



    // int[128]
    // 1ms, 100%; 40.4 MB, 95.57%
    public char findTheDifference(String s, String t) {
        int[] freq = new int[128];

        for ( char c : s.toCharArray()) {
            freq[c]++;
        }

        for (char c : t.toCharArray()) {
            freq[c]--;
            if (freq[c] < 0) return c;
        }

        return '#';

    }


    public static void main(String[] args) {
        FindStringDifference solution = new FindStringDifference();
        String s = "abcd";
        String t = "abcde";
        char difference = solution.findTheDifference(s, t);
        System.out.println("Added character: " + difference); // Output: 'e'
    }


}
