package com.sjia.Leetcode;

public class FindtheDifference {

    // #389 https://leetcode.com/problems/find-the-difference/
    // String t is generated by random shuffling string s
    // and then add one more letter at a random position.

    // Runtime: 1 ms, faster than 99.65% of Java online submissions for Find the Difference.
    //Memory Usage: 39.7 MB, less than 5.71% of Java online submissions for Find the Difference.
/*
    public char findTheDifference(String s, String t) {
        int sum = 0;
        for ( int i=0; i < s.length(); i++) {
            sum +=  t.charAt(i) - s.charAt(i);
        }
        sum += t.charAt(s.length());
        return (char) sum;
    }*/


    // Runtime: 1 ms, faster than 99.65% of Java online submissions for Find the Difference.
    //Memory Usage: 39.3 MB, less than 5.71% of Java online submissions for Find the Difference.
/*
    public char findTheDifference(String s, String t) {
        int sum = 0;
        char[] a = s.toCharArray();
        char[] b = t.toCharArray();
        for ( int i=0; i < s.length(); i++) {
            sum +=  b[i] - a[i];
        }
        sum += b[s.length()];
        return (char) sum;
    }*/


    // xor
    // Runtime: 1 ms, faster than 99.65% of Java online submissions for Find the Difference.
    //Memory Usage: 37.7 MB, less than 46.43% of Java online submissions for Find the Difference.
    public char findTheDifference(String s, String t) {
        int result = 0;
        for ( int i=0; i < s.length(); i++) {
            result = result ^ s.charAt(i) ^ t.charAt(i);
        }
        result = result ^ t.charAt(s.length());
        return  (char)result;
    }


    // Runtime: 1 ms, faster than 99.65% of Java online submissions for Find the Difference.
    //Memory Usage: 37.7 MB, less than 51.43% of Java online submissions for Find the Difference.
    public static void main(String[] args) {
        String s  = "abcd";
        String t = "abcde";
        FindtheDifference solution = new FindtheDifference();
        char result = solution.findTheDifference(s, t);

        System.out.printf("s: %s  and t: %s findTheDifference %s \n",
                s,t, result);
    }

/*
    public char findTheDifference(String s, String t) {
        int result = 0;
        for ( int i=0; i < s.length(); i++) {
            result = result ^ s.charAt(i) ^ t.charAt(i);
        }
        result = result ^ t.charAt(s.length());
        return  (char)result;
    }*/


}
